# CMake generated Testfile for 
# Source directory: /home/nilesh/Desktop/plibsys/plibsys/tests
# Build directory: /home/nilesh/Desktop/plibsys/ubuntu/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(patomic_test "/home/nilesh/Desktop/plibsys/ubuntu/patomic_test")
set_tests_properties(patomic_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;65;add_test;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;69;plibsys_add_test_executable;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;0;")
add_test(pcondvariable_test "/home/nilesh/Desktop/plibsys/ubuntu/pcondvariable_test")
set_tests_properties(pcondvariable_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;65;add_test;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;70;plibsys_add_test_executable;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;0;")
add_test(pcryptohash_test "/home/nilesh/Desktop/plibsys/ubuntu/pcryptohash_test")
set_tests_properties(pcryptohash_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;65;add_test;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;71;plibsys_add_test_executable;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;0;")
add_test(perror_test "/home/nilesh/Desktop/plibsys/ubuntu/perror_test")
set_tests_properties(perror_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;65;add_test;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;72;plibsys_add_test_executable;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;0;")
add_test(pdir_test "/home/nilesh/Desktop/plibsys/ubuntu/pdir_test")
set_tests_properties(pdir_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;65;add_test;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;73;plibsys_add_test_executable;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;0;")
add_test(pfile_test "/home/nilesh/Desktop/plibsys/ubuntu/pfile_test")
set_tests_properties(pfile_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;65;add_test;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;74;plibsys_add_test_executable;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;0;")
add_test(phashtable_test "/home/nilesh/Desktop/plibsys/ubuntu/phashtable_test")
set_tests_properties(phashtable_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;65;add_test;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;75;plibsys_add_test_executable;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;0;")
add_test(pinifile_test "/home/nilesh/Desktop/plibsys/ubuntu/pinifile_test")
set_tests_properties(pinifile_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;65;add_test;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;76;plibsys_add_test_executable;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;0;")
add_test(plibraryloader_test "/home/nilesh/Desktop/plibsys/ubuntu/plibraryloader_test" "--" "/home/nilesh/Desktop/plibsys/ubuntu/libplibsys.so.0")
set_tests_properties(plibraryloader_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;63;add_test;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;77;plibsys_add_test_executable;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;0;")
add_test(plist_test "/home/nilesh/Desktop/plibsys/ubuntu/plist_test")
set_tests_properties(plist_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;65;add_test;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;78;plibsys_add_test_executable;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;0;")
add_test(pmacros_test "/home/nilesh/Desktop/plibsys/ubuntu/pmacros_test")
set_tests_properties(pmacros_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;65;add_test;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;79;plibsys_add_test_executable;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;0;")
add_test(pmain_test "/home/nilesh/Desktop/plibsys/ubuntu/pmain_test")
set_tests_properties(pmain_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;65;add_test;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;80;plibsys_add_test_executable;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;0;")
add_test(pmem_test "/home/nilesh/Desktop/plibsys/ubuntu/pmem_test")
set_tests_properties(pmem_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;65;add_test;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;81;plibsys_add_test_executable;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;0;")
add_test(pmutex_test "/home/nilesh/Desktop/plibsys/ubuntu/pmutex_test")
set_tests_properties(pmutex_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;65;add_test;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;82;plibsys_add_test_executable;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;0;")
add_test(pprocess_test "/home/nilesh/Desktop/plibsys/ubuntu/pprocess_test")
set_tests_properties(pprocess_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;65;add_test;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;83;plibsys_add_test_executable;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;0;")
add_test(prwlock_test "/home/nilesh/Desktop/plibsys/ubuntu/prwlock_test")
set_tests_properties(prwlock_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;65;add_test;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;84;plibsys_add_test_executable;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;0;")
add_test(psemaphore_test "/home/nilesh/Desktop/plibsys/ubuntu/psemaphore_test")
set_tests_properties(psemaphore_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;65;add_test;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;85;plibsys_add_test_executable;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;0;")
add_test(pshmbuffer_test "/home/nilesh/Desktop/plibsys/ubuntu/pshmbuffer_test")
set_tests_properties(pshmbuffer_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;65;add_test;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;86;plibsys_add_test_executable;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;0;")
add_test(pshm_test "/home/nilesh/Desktop/plibsys/ubuntu/pshm_test")
set_tests_properties(pshm_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;65;add_test;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;87;plibsys_add_test_executable;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;0;")
add_test(psocket_test "/home/nilesh/Desktop/plibsys/ubuntu/psocket_test")
set_tests_properties(psocket_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;65;add_test;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;88;plibsys_add_test_executable;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;0;")
add_test(psocketaddress_test "/home/nilesh/Desktop/plibsys/ubuntu/psocketaddress_test")
set_tests_properties(psocketaddress_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;65;add_test;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;89;plibsys_add_test_executable;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;0;")
add_test(pspinlock_test "/home/nilesh/Desktop/plibsys/ubuntu/pspinlock_test")
set_tests_properties(pspinlock_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;65;add_test;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;90;plibsys_add_test_executable;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;0;")
add_test(pstdarg_test "/home/nilesh/Desktop/plibsys/ubuntu/pstdarg_test")
set_tests_properties(pstdarg_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;65;add_test;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;91;plibsys_add_test_executable;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;0;")
add_test(pstring_test "/home/nilesh/Desktop/plibsys/ubuntu/pstring_test")
set_tests_properties(pstring_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;65;add_test;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;92;plibsys_add_test_executable;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;0;")
add_test(ptimeprofiler_test "/home/nilesh/Desktop/plibsys/ubuntu/ptimeprofiler_test")
set_tests_properties(ptimeprofiler_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;65;add_test;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;93;plibsys_add_test_executable;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;0;")
add_test(ptree_test "/home/nilesh/Desktop/plibsys/ubuntu/ptree_test")
set_tests_properties(ptree_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;65;add_test;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;94;plibsys_add_test_executable;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;0;")
add_test(ptypes_test "/home/nilesh/Desktop/plibsys/ubuntu/ptypes_test")
set_tests_properties(ptypes_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;65;add_test;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;95;plibsys_add_test_executable;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;0;")
add_test(puthread_test "/home/nilesh/Desktop/plibsys/ubuntu/puthread_test")
set_tests_properties(puthread_test PROPERTIES  _BACKTRACE_TRIPLES "/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;65;add_test;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;96;plibsys_add_test_executable;/home/nilesh/Desktop/plibsys/plibsys/tests/CMakeLists.txt;0;")
